<?php 
return [
'cnf_appname' 			=> 'Sximo 6',
'cnf_appdesc' 			=> 'New Generation Application Builder',
'cnf_comname' 			=> 'Mangopik LTD',
'cnf_email' 			=> 'info@mycompanyname.com',
'cnf_metakey' 			=> 'my site , my company  , Larvel Crud',
'cnf_metadesc' 		=> 'Write description for your site',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '1',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'true',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6Le2bjQUAAAAABascn2t0WsRjZbmL6EnxFJUU1H_',
'cnf_recaptchaprivatekey' => '6Le2bjQUAAAAAI6ZKqgzoYS21umpeper74sMK38s',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'Y-m-d',
];
